### ISSUE TITLE
Use a crypted or hashed password in the config

### ISSUE THREAD

**Issue by Marc176** [ThomasLeister/webmum#39]
I dont think its safe to have a plaintext password for the mysql databas in the config file

**Comment by Marc176** [comment]
as an idea i found:

> 
> Personally, I store sensitive information such as database connection details in a config.ini file outside of my web folder’s root. Then in my index.php I can do:
> 
> $config = parse_ini_file('../config.ini');

**Comment by ohartl** [comment]
Here are three reasons why you don't need to worry:

First of all the config file does not output any information, since php scripts will be executed and there is no echo of such. But if you configure you webserver the wrong way, and make php files content downloadable, its your own fault.

And here just to explain why encryption of passwords in a config file are unnecessary:
The contents of the config file are only accessible from your filesystem.
To connect to the database the cleartext password is required.
And if you encrypt the db password in the config, you have to decrypt it before using it for creating the database connection. This requires an algorithm thats code must be hardcoded into webmum's code anyways. This way the encryption of the password isn't worth anything if your have the algorithm too.

As a general advice on database users, you should create db users for specific tasks only and restrict the  access to the database by IP's, and use one unique long password per user. For a webserver connection from the same server as the database, use localhost,127.0.0.1 only. So if you configure your users under that general security aspect, an attack that has no access to your filesystem cannot do anything with db user information.

Lastly if an attack has gained access to your filesystem, you are having a big problem anyways...

Hopefully that helped you.
